const o = [
  {
    id: 184,
    name: "Аксессуар для охоты и охотничьего оружия",
    code: "930320",
    quantity: "2",
    price: "3",
  },
  {
    id: 283,
    name: "Детектор Wi-Fi",
    code: "851762",
    quantity: "4",
    price: "40",
  },
  {
    id: 184,
    name: "Аксессуар для охоты и охотничьего оружия",
    code: "930320",
    quantity: "4",
    price: "200",
  },
  {
    id: 6,
    name: "Мужская кожаная куртка",
    code: "420310",
    quantity: "3",
    price: "50",
  },
  {
    id: 160,
    name: "Вибромассажер для похудения",
    code: "950691",
    quantity: "8",
    price: "80",
  },
  {
    id: 5,
    name: "Мужская куртка",
    code: "620120",
    quantity: "7",
    price: "60",
  },
  {
    id: 378,
    name: "Техника Wi-Fi",
    code: "851762",
    quantity: "5",
    price: "60",
  },
  {
    id: 297,
    name: "Powerline-адаптер",
    code: "851762",
    quantity: "3",
    price: "32",
  },
  {
    id: 54,
    name: "Женские колготки",
    code: "611521",
    quantity: "2",
    price: "23",
  },
  {
    id: 2,
    name: "Мужские джинсы",
    code: "620342",
    quantity: "20",
    price: "00200",
  },
  {
    id: 17,
    name: "Мужская футболка и поло",
    code: "610910",
    quantity: "3",
    price: "20",
  },
  {
    id: 1,
    name: "Мужская толстовка и свитшот",
    code: "611020",
    quantity: "3",
    price: "50",
  },
  {
    id: 52,
    name: "Женский комплект халатов и сорочек",
    code: "610839",
    quantity: "2",
    price: "5",
  },
  {
    id: 12,
    name: "Мужская домашняя одежда",
    code: "610721",
    quantity: "2",
    price: "222",
  },
  {
    id: 17,
    name: "Мужская футболка и поло",
    code: "610910",
    quantity: "2",
    price: "515",
  },
  {
    id: 88,
    name: "Школьная форма",
    code: "610322",
    quantity: "4",
    price: "60",
  },
  {
    id: 4,
    name: "Мужской жилет и безрукавка",
    code: "611030",
    quantity: "6",
    price: "80",
  },
  {
    id: 1,
    name: "Мужская толстовка и свитшот",
    code: "611020",
    quantity: "6",
    price: "500",
  },
  {
    id: 1,
    name: "Мужская толстовка и свитшот",
    code: "611020",
    quantity: "5",
    price: "50",
  },
  {
    id: 4,
    name: "Мужской жилет и безрукавка",
    code: "611030",
    quantity: "65",
    price: "800",
  },
];

export default o;
